# Generated by Django 5.0.4 on 2024-05-06 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_product_arrival_arrival_shipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="product",
        ),
        migrations.DeleteModel(
            name="Arrival",
        ),
        migrations.DeleteModel(
            name="Shipment",
        ),
    ]
