# Generated by Django 5.0.4 on 2024-05-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_shipment_product_delete_arrival_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="product_shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reciever", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True)),
                ("quantity", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
