# Generated by Django 5.0.4 on 2024-05-18 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_product_shipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
