# Generated by Django 5.0.4 on 2024-05-18 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_product_arrival_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 5, 18, 22, 45, 50, 931140)
            ),
        ),
    ]
