# Generated by Django 5.0.4 on 2024-05-18 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_alter_product_arrival_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 5, 18, 23, 17, 6, 655498)
            ),
        ),
    ]
