# Generated by Django 5.0.6 on 2024-06-10 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_alter_product_arrival_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Import_products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("gtd_id", models.IntegerField()),
                ("date", models.DateField()),
                ("third_id", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-name"],
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-name"]},
        ),
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 10, 21, 31, 46, 661099)
            ),
        ),
    ]
