# Generated by Django 5.0.6 on 2024-06-18 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_import_products_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 18, 22, 23, 33, 783183)
            ),
        ),
    ]
