# Generated by Django 5.0.6 on 2024-06-18 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_alter_product_arrival_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 18, 22, 24, 44, 205219)
            ),
        ),
    ]
