# Generated by Django 5.0.6 on 2024-06-18 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_alter_product_arrival_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import_products",
            name="gtd_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 18, 22, 25, 43, 36865)
            ),
        ),
    ]
