# Generated by Django 5.0.6 on 2024-06-19 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_alter_import_products_gtd_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="import_product_shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reciever", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True)),
                ("quantity", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 19, 20, 51, 18, 256767)
            ),
        ),
    ]
