# Generated by Django 5.0.6 on 2024-06-19 16:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_rename_name_import_product_shipment_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="import_product_shipment",
            name="product",
            field=models.ForeignKey(
                default=2205,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.import_products",
            ),
        ),
        migrations.AlterField(
            model_name="import_product_shipment",
            name="date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 19, 21, 55, 9, 382829)
            ),
        ),
    ]
