# Generated by Django 5.0.6 on 2024-06-20 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_import_product_shipment_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="import_product_shipment",
            old_name="description",
            new_name="product_id",
        ),
        migrations.RemoveField(
            model_name="import_product_shipment",
            name="product",
        ),
        migrations.AddField(
            model_name="import_product_shipment",
            name="billing_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="import_product_shipment",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 20, 22, 57, 46, 606680)
            ),
        ),
    ]
