# Generated by Django 5.0.6 on 2024-06-20 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0021_rename_description_import_product_shipment_product_id_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="import_product_shipment",
        ),
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 20, 23, 0, 25, 345666)
            ),
        ),
    ]
