# Generated by Django 5.0.6 on 2024-06-20 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0022_delete_import_product_shipment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="import_product_shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reciever", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("quantity", models.IntegerField(default=0)),
                ("product_id", models.CharField(max_length=100)),
                ("billing_number", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 20, 23, 2, 42, 693909)
            ),
        ),
    ]
