# Generated by Django 5.0.6 on 2024-06-20 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0023_import_product_shipment_alter_product_arrival_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 20, 23, 6, 3, 815177)
            ),
        ),
    ]
