# Generated by Django 5.0.6 on 2024-06-22 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0024_alter_product_arrival_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="import_products",
            name="income_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 22, 10, 22, 50, 546178)
            ),
        ),
    ]
