# Generated by Django 5.0.6 on 2024-06-22 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0025_import_products_income_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import_products",
            name="name",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 22, 11, 51, 37, 496393)
            ),
        ),
    ]
