# Generated by Django 5.0.6 on 2024-06-22 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0026_alter_import_products_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="import_products",
            name="third_id",
        ),
        migrations.AlterField(
            model_name="product_arrival",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 6, 22, 14, 21, 13, 318881)
            ),
        ),
    ]
